CXX = clang
CXXFLAGS = -std=c++14

MAIN = \
main-maximum-flow-edmonds-karp \
main-maximum-flow-preflow-push-relabel-generic \
main-maximum-flow-preflow-push-relabel-highest \
main-maximum-flow-dinic \
main-maximum-flow-mpm

.PHONY: all clean
all: ${MAIN}
clean:
	rm -rf ${MAIN}