load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//:variables.bzl", "COPTS")
load("//main:variables.bzl", "DEPS")


HDRS = [ "template-segment-tree-interp.hpp", "template-segment-tree-interp-purq.hpp" ]

cc_binary(
    name = "amount",
    srcs = [ "main-amount.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "gcd",
    srcs = [ "main-gcd.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "kth-zero",
    srcs = [ "main-kth-zero.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "lcm",
    srcs = [ "main-lcm.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "maximum",
    srcs = [ "main-maximum.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "maxsum",
    srcs = [ "main-maxsum.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "maxtimes",
    srcs = [ "main-maxtimes.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "prefix-amount",
    srcs = [ "main-prefix-amount.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "range-add-point-query",
    srcs = [ "main-range-add-point-query.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "range-add-range-max",
    srcs = [ "main-range-add-range-max.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "range-assign-point-query",
    srcs = [ "main-range-assign-point-query.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "segment-tree-2d",
    srcs = [ "main-segment-tree-2d.cpp" ],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "segment-tree-persistent",
    srcs = [ "main-segment-tree-persistent.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "smallest-greater",
    srcs = [ "main-smallest-greater.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "sum",
    srcs = [ "main-sum.cpp" ] + HDRS,
    copts = COPTS,
    deps = DEPS,
)

