CXX = clang++
CXXFLAGS = -std=c++14

MAIN = main-binary-indexed-tree \
main-binary-indexed-tree-min \
main-binary-indexed-tree-2d \
main-binary-indexed-tree-rupq \
main-binary-indexed-tree-rurq \
main-binary-indexed-tree-2d-sparse

.PHONY: all clean
all: ${MAIN}
clean:
	rm -f ${MAIN}