load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//:variables.bzl", "COPTS")
load("//main:variables.bzl", "DEPS")

cc_binary(
    name = "union-rectangle-area",
    srcs = ["main-union-rectangle-area.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "vector2",
    srcs = ["main-vector2.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "vector3",
    srcs = ["main-vector3.cpp"],
    copts = COPTS,
    deps = DEPS,
)
