version: 2.0
jobs:
  compile:
    docker:
      - image: gcc:latest
        auth:
              username: $DOCKERHUB_USERNAME
              password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: cd lib && make -j $(nproc) all

workflows:
  version: 2
  build:
    jobs:
      - compile