version: 2.1

executors:
  cpalgo:
    docker:
      - image: xirc/cp-algorithm
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

jobs:
  bazel-lint:
    executor: cpalgo
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-{{ .Branch }}-{{ .Revision }}
            - bazel-{{ .Branch }}
            - bazel
      - run:
          name: Lint All
          command: |
            buildifier --mode=diff --lint=warn --warnings=all -r lib
  build:
    executor: cpalgo
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-{{ .Branch }}-{{ .Revision }}
            - bazel-{{ .Branch }}
            - bazel
      - run:
          name: Build All
          command: |
            cd lib
            bazelisk build --jobs=HOST_RAM //cpalgo/...:* //main/...:*
  test:
    executor: cpalgo
    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-{{ .Branch }}-{{ .Revision }}
            - bazel-{{ .Branch }}
            - bazel
      - run:
          name: Test library
          command: |
            cd lib
            bazelisk test --jobs=HOST_RAM //cpalgo/...:*
      - save_cache:
          key: bazel-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.cache/bazel

workflows:
  version: 2
  build:
    jobs:
      - bazel-lint:
          context:
            - docker-hub
      - build:
          requires:
            - bazel-lint
          context:
            - docker-hub
      - test:
          requires:
            - build
          context:
            - docker-hub