load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//:variables.bzl", "COPTS")
load("//main:variables.bzl", "DEPS")

cc_binary(
    name = "cartesian-tree-construction",
    srcs = ["main-cartesian-tree-construction.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "disjoint-sparse-table",
    srcs = ["main-disjoint-sparse-table.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "implicit-treap",
    srcs = ["main-implicit-treap.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "kdtree",
    srcs = ["main-kdtree.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "minmax-queue",
    srcs = ["main-minmax-queue.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "minmax-stack",
    srcs = ["main-minmax-stack.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "randomized-heap",
    srcs = ["main-randomized-heap.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "treap",
    srcs = ["main-treap.cpp"],
    copts = COPTS,
    deps = DEPS,
)
