load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//:variables.bzl", "COPTS")
load("//main:variables.bzl", "DEPS")

cc_binary(
    name = "binary-indexed-tree-2d-sparse",
    srcs = ["main-binary-indexed-tree-2d-sparse.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "binary-indexed-tree-2d",
    srcs = ["main-binary-indexed-tree-2d.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "binary-indexed-tree-min",
    srcs = ["main-binary-indexed-tree-min.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "binary-indexed-tree-rupq",
    srcs = ["main-binary-indexed-tree-rupq.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "binary-indexed-tree-rurq",
    srcs = ["main-binary-indexed-tree-rurq.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "binary-indexed-tree",
    srcs = ["main-binary-indexed-tree.cpp"],
    copts = COPTS,
    deps = DEPS,
)
