load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//:variables.bzl", "COPTS")
load("//main:variables.bzl", "DEPS")


cc_binary(
    name = "max-query",
    srcs = [ "main-max-query.cpp" ],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "sum-query",
    srcs = [ "main-max-query.cpp" ],
    copts = COPTS,
    deps = DEPS,
)
