# TODO Remove -fpermissinve and change compiler clang++
CXX = c++
CXXFLAGS = -std=c++14 -fpermissive

MAIN = main-sum main-maximum main-maxtimes \
main-gcd main-lcm main-kth-zero main-prefix-amount \
main-amount main-maxsum main-smallest-greater \
main-range-add-point-query main-range-assign-point-query \
main-range-add-range-max main-segment-tree-2d main-persistent-segment-tree

.PHONY: all clean
all: ${MAIN}
clean:
	rm -f ${MAIN}