load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//:variables.bzl", "COPTS")
load("//main:variables.bzl", "DEPS")

cc_binary(
    name = "articulation-points",
    srcs = ["main-articulation-points.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "bridges",
    srcs = ["main-bridges.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "finding-cycle",
    srcs = ["main-finding-cycle.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "minimum-cost-arborescence",
    srcs = ["main-minimum-cost-arborescence.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "minimum-cost-flow",
    srcs = ["main-minimum-cost-flow.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "strongly-connected-components",
    srcs = ["main-strongly-connected-components.cpp"],
    copts = COPTS,
    deps = DEPS,
)

cc_binary(
    name = "topological-sort",
    srcs = ["main-topological-sort.cpp"],
    copts = COPTS,
    deps = DEPS,
)
