CXX = g++
CXXFLAGS = -std=c++14

MAIN = \
main-floyd-warshall \
main-num-path-of-fixed-length \
main-num-path-with-length-upto \
main-shortest-path-of-fixed-length \
main-shortest-path-with-length-upto

.PHONY: all clean
all: ${MAIN}
clean:
	rm -f ${MAIN}