load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//:variables.bzl", "COPTS")
load("//main:variables.bzl", "DEPS")

cc_binary(
    name = "bigint",
    srcs = ["main-bigint.cpp"],
    copts = COPTS,
    deps = DEPS,
)
